name: Project Contract Enforcement

on:
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read
  pull-requests: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check docs & specs
        run: |
          test -d docs || (echo "❌ Missing /docs" && exit 1)
          test -d specs || (echo "❌ Missing /specs" && exit 1)
          test -f .aiconfig.md || (echo "❌ Missing .aiconfig.md" && exit 1)

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [ "node", "python" ]
    steps:
      - uses: actions/checkout@v4

      - name: Node.js tests
        if: matrix.language == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - if: matrix.language == 'node'
        run: npm ci && npm test

      - name: Python tests
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - if: matrix.language == 'python'
        run: pip install -r requirements.txt && pytest -q

  postman-tests:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm install -g newman
      - run: newman run postman/collection.json \
            --env-var baseUrl=http://localhost:3000 \
            --reporters cli,junit \
            --reporter-junit-export postman-results.xml